package sistemparkir.view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package sistemparkir.view;
import sistemparkir.model.Kendaraan;
import sistemparkir.view.DaftarParkir;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sistemparkir.dao.ParkirDAO;
import sistemparkir.model.Kendaraan;
import sistemparkir.view.FormPembayaran;

  //  private void FormParkir(id){
  //      throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
  // }

  //  private void dispose(){
  //      throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
  //  }
/**
 *
 * @author 62878
 */
public class FormParkir extends javax.swing.JFrame {
        Kendaraan kendaraan;
        private Integer id;
        private DaftarParkir parent; 
        private ParkirDAO pdao = new ParkirDAO();

        public FormParkir(DaftarParkir parent, Integer id) {
            initComponents();
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            this.parent = parent;
            this.id = id;

            if (id != null) {
                setTitle("Ubah Data Parkir");
                loadData();
            } else {
                setTitle("Tambah Kendaraan Masuk");
            }
        }

        public FormParkir() {
            initComponents();
        }

        private void loadData() {
            Kendaraan k = pdao.getById(id);
            if (k != null) {
                txtPlatNomor.setText(k.getPlatNomor());
                txtGolongan.setText(String.valueOf(k.getGolongan()));
            }
        }

    FormParkir(Integer id) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        txtPlatNomor = new javax.swing.JTextField();
        txtGolongan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnMasuk = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtPlatNomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlatNomorActionPerformed(evt);
            }
        });
        getContentPane().add(txtPlatNomor);
        txtPlatNomor.setBounds(171, 78, 204, 26);

        txtGolongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGolonganActionPerformed(evt);
            }
        });
        getContentPane().add(txtGolongan);
        txtGolongan.setBounds(171, 141, 204, 26);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Form Parkir");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 260, 250, 48);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Plat Nomor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 80, 120, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Golongan");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 140, 90, 25);

        btnMasuk.setBackground(new java.awt.Color(102, 102, 255));
        btnMasuk.setText("Masuk");
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });
        getContentPane().add(btnMasuk);
        btnMasuk.setBounds(185, 197, 76, 27);

        btnBatal.setBackground(new java.awt.Color(255, 51, 51));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal);
        btnBatal.setBounds(230, 242, 76, 27);

        btnKeluar.setBackground(new java.awt.Color(255, 204, 51));
        btnKeluar.setForeground(new java.awt.Color(0, 0, 0));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(281, 197, 76, 27);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JAVBA/BG1.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-10, -10, 480, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        
        try {
            
            Kendaraan k = new Kendaraan();
            k.setPlatNomor(txtPlatNomor.getText());
            k.setGolongan(Integer.parseInt(txtGolongan.getText()));

            boolean sukses;
            if (id == null) {
                sukses = pdao.insert(k);
            } else {
                k.setIdKendaraan(id);
                sukses = pdao.update(k);
            }

            if (sukses) {
                JOptionPane.showMessageDialog(this, "Data Berhasil disimpan!");
                if (parent != null) parent.loadData();
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Golongan harus berupa angka!");
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_btnMasukActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
      dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtPlatNomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlatNomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlatNomorActionPerformed

    private void txtGolonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGolonganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGolonganActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        if (id == null) {
                    JOptionPane.showMessageDialog(this, "Simpan data atau pilih data terlebih dahulu!");
                } else {
                    FormPembayaran fp = new FormPembayaran(id);
                    fp.setVisible(true);
                    dispose();
                }
                             // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormParkir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnMasuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField txtGolongan;
    private javax.swing.JTextField txtPlatNomor;
    // End of variables declaration//GEN-END:variables
}
