package sistemparkir.view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package sistemparkir.view;
import javax.swing.JOptionPane;
import sistemparkir.dao.ParkirDAO;
import sistemparkir.model.*;

public class FormParkir extends javax.swing.JFrame {
    private DaftarParkir parent;
    private Integer idParkir;
    private Object[] dataParkir;
    private ParkirDAO pdao = new ParkirDAO();
    private javax.swing.JComboBox<String> cmbGolongan;

    
    public FormParkir (){}
    
    
    public FormParkir(DaftarParkir parent, Integer idParkir, Object[] dataParkir) {
        initComponents();
        this.parent = parent;
        this.idParkir = idParkir;
        this.dataParkir = dataParkir;
        
        setLocationRelativeTo(parent);
        
        if (idParkir != null && dataParkir != null) {
            setTitle("Ubah Data Parkir");
            loadData();
            btnKeluar.setVisible(true);
        } else {
            setTitle("Tambah Kendaraan Masuk");
            cmbGolongan.setSelectedIndex(0);
            btnKeluar.setVisible(false);
        }
    }

    private void loadData() {
        if (dataParkir != null) {
            txtPlatNomor.setText(dataParkir[1].toString());
            
            try {
                int golongan = Integer.parseInt(dataParkir[2].toString());
                for (int i = 0; i < cmbGolongan.getItemCount(); i++) {
                    if (cmbGolongan.getItemAt(i).startsWith(golongan + " -")) {
                        cmbGolongan.setSelectedIndex(i);
                        break;
                    }
                }
            } catch (NumberFormatException e) {
                cmbGolongan.setSelectedIndex(0);
            }
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        txtPlatNomor = new javax.swing.JTextField();
        txtGolongan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnMasuk = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JAVBA/BG1.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        txtPlatNomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlatNomorActionPerformed(evt);
            }
        });
        getContentPane().add(txtPlatNomor);
        txtPlatNomor.setBounds(171, 78, 204, 22);

        txtGolongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGolonganActionPerformed(evt);
            }
        });
        getContentPane().add(txtGolongan);
        txtGolongan.setBounds(171, 141, 204, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Form Parkir");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 0, 250, 48);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Plat Nomor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 80, 120, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Golongan");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 140, 90, 25);

        btnMasuk.setBackground(new java.awt.Color(102, 102, 255));
        btnMasuk.setText("Masuk");
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });
        getContentPane().add(btnMasuk);
        btnMasuk.setBounds(185, 197, 72, 23);

        btnBatal.setBackground(new java.awt.Color(255, 51, 51));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal);
        btnBatal.setBounds(230, 242, 72, 23);

        btnKeluar.setBackground(new java.awt.Color(255, 204, 51));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(281, 197, 72, 23);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 100, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/WhatsApp Image 2026-01-14 at 10.15.12.jpeg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 510, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        
        String platNomor = txtPlatNomor.getText().trim();
        
        if (platNomor.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Plat nomor harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            int golongan = cmbGolongan.getSelectedIndex() + 1;
            Kendaraan kendaraan = pdao.createKendaraanByGolongan(0, platNomor, golongan);
            
            boolean success;
            if (idParkir == null) {
                success = pdao.insert(kendaraan);
                if (success) {
                    success = pdao.insertParkir(kendaraan);
                    if (success) {
                        JOptionPane.showMessageDialog(this, 
                            "Kendaraan berhasil masuk!\n" +
                            "Plat: " + platNomor + "\n" +
                            "Golongan: " + cmbGolongan.getSelectedItem(),
                            "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            } else {
                kendaraan.setIdKendaraan(Integer.parseInt(dataParkir[0].toString()));
                success = pdao.updateKendaraan(kendaraan);
                if (success) {
                    JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
            if (success) {
                if (parent != null) {
                    parent.loadData();
                }
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_btnMasukActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
      dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtPlatNomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlatNomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlatNomorActionPerformed

    private void txtGolonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGolonganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGolonganActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        if (idParkir == null) {
            JOptionPane.showMessageDialog(this, "Simpan data terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            int confirm = JOptionPane.showConfirmDialog(this, 
                "Proses keluar parkir?\nPlat: " + txtPlatNomor.getText(),
                "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
            
            if (confirm == JOptionPane.YES_OPTION) {
                double totalBayar = pdao.prosesKeluarParkir(idParkir);
                if (totalBayar >= 0) {
                    String message;
                    if (totalBayar == 0) {
                        message = "Parkir selesai!\nTotal Bayar: GRATIS (Mahasiswa)";
                    } else {
                        message = "Parkir selesai!\nTotal Bayar: Rp " + totalBayar;
                    }
                    
                    JOptionPane.showMessageDialog(this, message, "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    
                    if (parent != null) {
                        parent.loadData();
                    }
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal memproses keluar parkir!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }               // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormParkir(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnMasuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField txtGolongan;
    private javax.swing.JTextField txtPlatNomor;
    // End of variables declaration//GEN-END:variables
}
