



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemparkir.view;

import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import sistemparkir.config.Database;
import sistemparkir.dao.ParkirDAO;
import sistemparkir.model.Kendaraan;

public class FormPembayaran extends javax.swing.JFrame {
    
    private Integer idParkir;
    private ParkirDAO pdao = new ParkirDAO();
    
    
    public FormPembayaran(Integer idParkir) {
        initComponents();
        this.idParkir = idParkir;
        
        if (idParkir != null) {
            tampilkanDataDanHitung();
        }
        
        setLocationRelativeTo(null);
    }

    private void tampilkanDataDanHitung() {
        try (Connection conn = Database.getConnection()) {
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Tidak dapat terhubung ke database!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            String sql = "SELECT p.*, k.jenis FROM parkir p " +
                        "LEFT JOIN kendaraan k ON p.id_kendaraan = k.id " +
                        "WHERE p.id = ?";
            
            try (PreparedStatement st = conn.prepareStatement(sql)) {
                st.setInt(1, idParkir);
                
                try (ResultSet rs = st.executeQuery()) {
                    if (rs.next()) {
                        txtPlat.setText(rs.getString("plat_nomor"));
                        
                        int golongan = rs.getInt("golongan");
                        txtGol.setText(getNamaGolongan(golongan));
                        txtMasuk.setText(formatDateTime(rs.getTimestamp("waktu_masuk")));
                        
                        LocalDateTime sekarang = LocalDateTime.now();
                        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
                        txtKeluar.setText(sekarang.format(dtf));
                        
                        Timestamp waktuMasuk = rs.getTimestamp("waktu_masuk");
                        LocalDateTime masuk = waktuMasuk.toLocalDateTime();
                        
                        long durasiMenit = java.time.Duration.between(masuk, sekarang).toMinutes();
                        long durasiJam = (long) Math.ceil(durasiMenit / 60.0);
                        if (durasiJam <= 0) durasiJam = 1;
                        
                        Kendaraan kendaraan = pdao.createKendaraanByGolongan(0, rs.getString("plat_nomor"), golongan);
                        double totalBayar = kendaraan.hitungTarif((int) durasiJam);
                        
                        txtLama.setText(durasiJam + " Jam");
                        
                        if (totalBayar == 0) {
                            txtTarif.setText("GRATIS (Mahasiswa)");
                            txtTarif.setForeground(new java.awt.Color(0, 128, 0));
                        } else {
                            txtTarif.setText("Rp " + formatRupiah(totalBayar));
                            txtTarif.setForeground(new java.awt.Color(51, 153, 0));
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Data tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
                        dispose();
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    private String getNamaGolongan(int golongan) {
        switch (golongan) {
            case 1: return "Mahasiswa (Gratis)";
            case 2: return "Motor";
            case 3: return "Mobil";
            case 4: return "Truck";
            default: return "Tidak diketahui";
        }
    }
    
    private String formatDateTime(Timestamp timestamp) {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
        return timestamp.toLocalDateTime().format(dtf);
    }
    
    private String formatRupiah(double amount) {
        return String.format("%,.0f", amount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPlat = new javax.swing.JTextField();
        txtGol = new javax.swing.JTextField();
        txtMasuk = new javax.swing.JTextField();
        txtKeluar = new javax.swing.JTextField();
        txtLama = new javax.swing.JTextField();
        txtTarif = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        btnSelesai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("No Plat");

        jLabel2.setText("Golongan");

        jLabel3.setText("Jam Masuk");

        jLabel4.setText("Jam Keluar");

        jLabel5.setText("Lama Parkir");

        jLabel6.setText("Total Tarif");

        jLabel7.setText("PEMBAYARAN");

        txtPlat.addActionListener(this::txtPlatActionPerformed);

        txtGol.addActionListener(this::txtGolActionPerformed);

        txtMasuk.addActionListener(this::txtMasukActionPerformed);

        txtKeluar.addActionListener(this::txtKeluarActionPerformed);

        txtLama.addActionListener(this::txtLamaActionPerformed);

        txtTarif.addActionListener(this::txtTarifActionPerformed);

        btnBatal.setText("Batal");
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(this::btnSelesaiActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTarif))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtLama))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(23, 23, 23)
                                .addComponent(txtMasuk))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGol)
                                    .addComponent(txtPlat)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(23, 23, 23)
                                .addComponent(txtKeluar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel7)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(btnBatal)
                .addGap(55, 55, 55)
                .addComponent(btnSelesai)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal)
                    .addComponent(btnSelesai))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlatActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtGolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGolActionPerformed

    private void txtMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMasukActionPerformed

    private void txtKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeluarActionPerformed

    private void txtLamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLamaActionPerformed

    private void txtTarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarifActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
    try {
            double totalBayar = pdao.prosesKeluarParkir(idParkir);
            
            if (totalBayar >= 0) {
                String message;
                if (totalBayar == 0) {
                    message = "Pembayaran berhasil!\nTotal Bayar: GRATIS (Mahasiswa)";
                } else {
                    message = "Pembayaran berhasil!\nTotal Bayar: Rp " + formatRupiah(totalBayar);
                }
                
                JOptionPane.showMessageDialog(this, message, "Sukses", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memproses pembayaran!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } //TODO add your handling code here:
    }//GEN-LAST:event_btnSelesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPembayaran(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtGol;
    private javax.swing.JTextField txtKeluar;
    private javax.swing.JTextField txtLama;
    private javax.swing.JTextField txtMasuk;
    private javax.swing.JTextField txtPlat;
    private javax.swing.JTextField txtTarif;
    // End of variables declaration//GEN-END:variables

